font_family                   Cascadia Code Nerd Font Propo
font_size                     14
enable_audio_bell             no
shell                         zsh
cursor_shape                  block
url_style                     curly
remember_window_size          no
initial_window_width          640
initial_window_heiht          480
window_padding_width          15
cursor_blink_interval         0
background_opacity            0.65
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0

#colors 
include colors.conf
