-- Generated by Wallust

return {

    background = "{{background}}",
    foreground = "{{foreground}}",

    color0 = "{{color0}}",
    color1 = "{{color1}}",
    color2 = "{{color2}}",
    color3 = "{{color3}}",
    color4 = "{{color4}}",
    color5 = "{{color5}}",
    color6 = "{{color6}}",
    color7 = "{{color7}}",

    color8 = "{{color8}}",
    color9 = "{{color9}}",
    color10 = "{{color10}}",
    color11 = "{{color11}}",
    color12 = "{{color12}}",
    color13 = "{{color13}}",
    color14 = "{{color14}}",
    color15 = "{{color15}}",

    ----------------------------------------------------
    -- Backgrounds
    ----------------------------------------------------

    bg = "alpha({{background}},0.82)",
    bg_solid = "alpha({{background}},0.95)",
    bg_light = "alpha({{background}},0.65)",

    module = "alpha({{background}},0.90)",
    module_hover = "alpha({{background}},0.98)",

    ----------------------------------------------------
    -- Text
    ----------------------------------------------------

    text = "{{foreground}}",
    text_muted = "{{color7}}",

    ----------------------------------------------------
    -- Accents
    ----------------------------------------------------

    accent = "{{color4}}",
    accent2 = "{{color5}}",

    success = "{{color2}}",
    warning = "{{color3}}",
    danger = "{{color1}}",
    info = "{{color6}}",

    ----------------------------------------------------
    -- Borders
    ----------------------------------------------------

    border = "{{color8}}",

    ----------------------------------------------------
    -- Gradient
    ----------------------------------------------------

    grad1 = "{{color4}}",
    grad2 = "{{color5}}",
    grad3 = "{{color6}}",
    grad4 = "{{color2}}",

}