general{
    hide_cursor= true
    ignore_empty_input = true

}
animation{
    
}
background{
    monitor =
    path= screenshot
    blur_passes= 2
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0

}
#password_box
input-field {
    size = 250, 60
    outline_thickness = 0.5
    outer_color = 
    inner_color =
    font_color =
    fade_on_empty = true
    placeholder_text =<i>Enter Password</i>
    fail_color =
    fail_text = <i>Wrong Password <b>($ATTEMPTS)</b></i>
    hide_input = true
    position = 0, 0 
    halign = center
    valign = center
    rounding = -1
    capslock_color = -1
    fail_timeout = 1500


}
#date
label {
    monitor =
    text 
    color = 
    font_size = 14
    font_family = Cascadia Code Nerd Font Propo
    position = 30, 0
    halign = left
    valign = top
}
#time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = 
    font_size = 17
    font_family = Cascadia Code Nerd Font Propo
    position = 150 ,30
    halign = left
    valign = top 
}