-- Generated by Wallust

return {

    background = "#152F08",
    foreground = "#DDDFDA",

    color0 = "#B0B2AB",
    color1 = "#EDF25D",
    color2 = "#E88EA8",
    color3 = "#C5E240",
    color4 = "#C7D53E",
    color5 = "#BCC832",
    color6 = "#DB7C2A",
    color7 = "#6C6D40",

    color8 = "#A7AA64",
    color9 = "#EDF25D",
    color10 = "#E88EA8",
    color11 = "#C5E240",
    color12 = "#C7D53E",
    color13 = "#BCC832",
    color14 = "#DB7C2A",
    color15 = "#EFF0BF",

    ----------------------------------------------------
    -- Backgrounds
    ----------------------------------------------------

    bg = "alpha(#152F08,0.82)",
    bg_solid = "alpha(#152F08,0.95)",
    bg_light = "alpha(#152F08,0.65)",

    module = "alpha(#152F08,0.90)",
    module_hover = "alpha(#152F08,0.98)",

    ----------------------------------------------------
    -- Text
    ----------------------------------------------------

    text = "#DDDFDA",
    text_muted = "#6C6D40",

    ----------------------------------------------------
    -- Accents
    ----------------------------------------------------

    accent = "#C7D53E",
    accent2 = "#BCC832",

    success = "#E88EA8",
    warning = "#C5E240",
    danger = "#EDF25D",
    info = "#DB7C2A",

    ----------------------------------------------------
    -- Borders
    ----------------------------------------------------

    border = "#A7AA64",

    ----------------------------------------------------
    -- Gradient
    ----------------------------------------------------

    grad1 = "#C7D53E",
    grad2 = "#BCC832",
    grad3 = "#DB7C2A",
    grad4 = "#E88EA8",

}